spring:
  datasource:
    url: jdbc:mysql://sakamichi.cpbhpim9yaco.ap-northeast-1.rds.amazonaws.com/sakamichi
    username: admin
    password: KzW1X8j7obHYa52GNQC1

mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true